runtime: nodejs16
service: server
instance_class: B1

basic_scaling:
  max_instances: 1
  idle_timeout: 3m

network:
  session_affinity: true

env_variables:
  CLIENT_HOST: "https://vofi-dig.lm.r.appspot.com"
  LUMI_HOST: "https://dig.luminight.dev"
